[cproject.toml]
version = "0.5.1"

[project]
name = "toml2make"
version = "0.3.0"
license = "MIT OR GPL-3.0-or-later"
description = "A tool to convert TOML files to Makefiles, for C/C++ projects."
author = "Arsalan 'Aeri' Kazmi"

[compiler]
cc = "gcc"
cflags = "-Wall -Wextra -Wpedantic"
cversion = "gnu17"

[paths]
install = "~/.local/bin/"

[options]
file_extension = "c"
use_include = true