[project]
name = "toml2make"
version = "0.1.0"
license = "MIT"
description = "A tool to convert TOML files to Makefiles, for C/C++ projects."
[compiler]
cc = "gcc"
cflags = [
    "-Wall",
    "-Wextra",
    "-Wpedantic",
]
cversion = "c17"

[build]
prefix = "$HOME/.local"