# Makefile generated by TOML To Makefile.
# Generated on 2024-10-28 at 16:41:28 UTC.
# For more information, see <https://github.com/AeriaVelocity/toml2make>

NAME = toml2make
VERSION = 0.1.0
LICENSE = MIT
DESCRIPTION = A tool to convert TOML files to Makefiles, for C/C++ projects.
AUTHOR = Arsalan 'Aeri' Kazmi

CC = gcc
CFLAGS = -Wall -Wextra -Wpedantic --std=gnu17
CVERSION = gnu17

prefix ?= ~/.local
SRC_DIR = src
BUILD_DIR = build
BIN_DIR = bin
TARGET = $(BIN_DIR)/$(NAME)

SRC = $(wildcard $(SRC_DIR)/*.c)
OBJ = $(SRC:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	@mkdir -p $(BIN_DIR)
	$(CC) -o $@ $^

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

run: all
	./$(TARGET)

clean:
	rm -rf $(BUILD_DIR)

.PHONY: all run clean
