# This is an UNSUPPORTED cproject.toml schema, kept here for posterity.
# DO NOT use this schema in any current projects.

[toml2make]
version = "0.4.0"

[project]
name = "your-project-name"
version = "0.1.0"
license = "ISC"
description = "A brief description of your project."
author = "Your Name"

[compiler]
cc = "gcc"
cflags = "-Wall -Wextra -Wpedantic"
cversion = "c17"

[build]
install = "~/.local/bin/"
build = "build"
src = "src"
bin = "bin"

[makefile]

out = "Makefile"