# There is a more recent minor version of this schema.
# This schema will still work but is not recommended -
# please use the newer version.

[toml2make.schema]
version = "0.5.0"

[project]
name = "your-project-name"
version = "0.1.0"
license = "ISC"
description = "A brief description of your project."
author = "Your Name"

[compiler]
cc = "gcc"
cflags = "-Wall -Wextra -Wpedantic"
cversion = "c17"

[options]
file_extension = "c"
use_include = true

[paths]
build = "build"
src = "src"
bin = "bin"
include = "include"
install = "~/.local/bin/"
makefile = "Makefile"