# This is an UNSUPPORTED cproject.toml schema, kept here for posterity.
# DO NOT use this schema in any current projects.

[project]
name = "your-project-name"
version = "0.1.0"
license = "ISC"
description = "A brief description of your project."
[compiler]
cc = "gcc"
cflags = [
    "-Wall",
    "-Wextra",
    "-Wpedantic",
]
cversion = "c17"

[build]
prefix = "$HOME/.local"
[makefile]
out = "Makefile"
log = "toml2make.log"